#Требования к сайту
---
functional:
 - Пользователь должен иметь возможность искать товары по ключевому слову или категории
 - Пользователь должен иметь возможность фильтровать товары
 - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
 - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
 - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
 - Сайт должен быть безопасным и защищать данные пользователя
 - Сайт должен иметь мобильную версию
 - Сайт нужно протестировать на совместимость с последними версиями браузеров
 - Важно, чтобы сайт мог обрабатывать большое количество трафика
 - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен соответствовать политики конфеденуиальности
  - Все кнопки взаимодействия с сайтом должны быть четко видны пользователю
  - В фильтрации по цене не должно быть возможнности ввода отрицательных чисел
  - Кнопки подтверждающие действия должнеы по цвету отличаться от кнопот отклоняющие действия.
  - общее оформление сайта браузерной версии не должно отличаться от мобильной
  - возможность поиска по категориям должна содержать только существующие категории
